name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest
    name: Create Release

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: dom, curl, libxml, mbstring, zip

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-dev --optimize-autoloader

      - name: Run tests
        run: |
          composer install --prefer-dist --no-progress
          composer test
          composer phpstan

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: |
            composer.json
            README.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  packagist:
    runs-on: ubuntu-latest
    name: Update Packagist
    needs: release
    if: github.repository == 'Horttcore/wp-block'

    steps:
      - name: Update Packagist
        run: |
          curl -XPOST -H'content-type:application/json' \
               'https://packagist.org/api/update-package?username=${{ secrets.PACKAGIST_USERNAME }}&apiToken=${{ secrets.PACKAGIST_TOKEN }}' \
               -d'{"repository":{"url":"https://github.com/${{ github.repository }}"}}'
